.PHONY: clean All

All:
	@echo "----------Building project:[ cTest1 - Debug ]----------"
	@cd "cTest1" && "$(MAKE)" -f  "cTest1.mk"
clean:
	@echo "----------Cleaning project:[ cTest1 - Debug ]----------"
	@cd "cTest1" && "$(MAKE)" -f  "cTest1.mk" clean
